apiVersion: apps/v1
kind: Deployment
metadata:
  name: upper-deployment
  labels:
    app: upper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upper
  template:
    metadata:
      labels:
        app: upper
    spec:
      containers:
        - name: upper
          image: t4lz/mirrord-demo
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: upper
  name: upper
spec:
  ports:
    - port: 30003
      protocol: TCP
      targetPort: 80
  selector:
    app: upper
  sessionAffinity: None
  type: LoadBalancer
